Bootstrap: docker
From: quay.io/biocontainers/bamtools:2.5.3--he132191_0

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@andrew.cmu.edu
    WEBSITE http://github.com/CBDatCMU/singularity-bamtools
    COPYRIGHT Copyright © 2026 Computational Biology Department. All Rights Reserved.
    VERSION 2.5.3

%help
    This container provides bamtools 2.5.3, a toolkit for BAM file manipulation.

    Usage:
        singularity exec image.sif bamtools <command> [options]

    Examples:
        singularity exec image.sif bamtools stats -in input.bam
        singularity exec image.sif bamtools sort -in input.bam -out sorted.bam

    Run `singularity exec image.sif bamtools --help` for full command reference.

%runscript
    exec bamtools "$@"

%test
    bamtools --version
